resilience4j.timelimiter:
  instances:
    working-with-sync:
      cancelRunningFuture: false
      timeoutDuration: 1s
    paymentService:
      cancelRunningFuture: true
      timeoutDuration: 1s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always