resilience4j.ratelimiter:
  instances:
    paymentService:
      limitForPeriod: 5
      limitRefreshPeriod: 5s
      timeoutDuration: 1s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always